//
//  HyperlinkEditor.h
//  RRMMailLink
//
//  Created by Reed on 1/3/14.
//  Copyright (c) 2014 Reed Mangino. All rights reserved.
//

//
//  Generated by class-dump 3.5 (64 bit).
//  class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
//  Ran against Mail.app version 7.1 (1827)
//

@interface HyperlinkEditor : NSObject
{
    NSTextField *_linkTextField;        // <-- the text field we will modify directly
    NSButton *_okButton;
    NSButton *_removeButton;
    EditingMessageWebView *_webView;
    id _delegate;
    DOMHTMLAnchorElement *_selectedAnchor;
    DOMNode *_selectionContents;
    NSString *_replacementLink;
    NSPanel *_linkSheet;
}

@property(retain, nonatomic) NSPanel *linkSheet;

- (void)_setReplacementLink:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)dealloc;
- (void)editLink;
- (id)initForWebView:(id)arg1 delegate:(id)arg2;
- (void)orderOutPanel:(id)arg1;
- (void)removeSelectedLink;

@end